# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 11:15
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20160201_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageserviceitem',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(),
        ),
    ]
