# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-18 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepagetestimonialitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonialitem',
            name='fb',
            field=models.URLField(blank=True, verbose_name='Embed video URL'),
        ),
    ]
