# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-16 15:46
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20160416_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeitem',
            name='ingredient',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
